package Java_lab3;
import java.util.*;
public class task7 {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        //  constants for ticket prices
        final int classA = 20;
        final int classB = 15;
        final int classC = 10;
        final int classD = 5;

        // taking inputs for the number of tickets sold for each class
        System.out.println("Enter the number of tickets sold for class A ");
        int classATickets = input.nextInt();

        System.out.println("Enter the number of tickets sold for class B ");
        int classBTickets = input.nextInt();

        System.out.println("Enter the number of tickets sold for class C ");
        int classCTickets = input.nextInt();

        System.out.println("Enter the number of tickets sold for class D ");
        int classDTickets = input.nextInt();

        int totalIncome = (classA*classATickets)+
                          (classB*classBTickets)+
                          (classC*classCTickets)+
                          (classD*classDTickets);

        System.out.println("Total income generated is: "+totalIncome);

        // income corresponding to each class
        System.out.println(" Income generated by class A:"+(classA*classATickets));
        System.out.println(" Income generated by class B:"+(classB*classBTickets));
        System.out.println(" Income generated by class C:"+(classC*classCTickets));
        System.out.println(" Income generated by class D:"+(classD*classDTickets));
    
    }
}
